version: '3.7'
services:

  redis-vector-db:
    build:
      context: ./redis-vector-db
      dockerfile: Dockerfile
    volumes:
      - ./redis-data:/data/
    ports:
      - 6379:6379
      - 8001:8001
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEPLOYMENT: "dev"
      REDIS_DATA_URL: 'redis://:testing123@redis-vector-db:6379/0'
      REDIS_OM_URL: 'redis://:testing123@redis-vector-db:6379/0'
      REDIS_HOST: 'redis-vector-db'
      REDIS_PORT: 6379
    expose:
      - "8888"
    ports:
      - "8888:8888"
    depends_on:
      - "redis-vector-db"

volumes:
  redis-vector-db: